<a href="https://colab.research.google.com/github/AdamJelley/AdventOfCode2021/blob/main/Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 4

In [44]:
import requests
import csv
import numpy as np

In [2]:
input_link = 'https://adventofcode.com/2021/day/4/input'
user_cookie = {'session':''} # Retrieve session cookie corresponding to user login (by inspecting cookies on data page)

In [284]:
raw_input = requests.get(input_link, cookies=user_cookie).text[:-1]
draws = [int(x) for x in raw_input.split('\n\n')[0].split(',')]
boards = [line.split('\n') for line in raw_input.split('\n\n')[1:]]
initial_boards_array = np.array([[[int(element) for element in line.strip().replace('  ', ' ').split(' ')] for line in board] for board in boards])

## Part 1

In [291]:
done=False
boards_array = np.copy(initial_boards_array)
for draw in draws:
  if not done:
    boards_array[boards_array==draw]=-1
    for i, board in enumerate(boards_array[:,...]):
      if np.any(board.sum(0)==boards_array.shape[1]*-1) or np.any(board.sum(1)==boards_array.shape[2]*-1):
        remaining_board_sum = board[board[:,:]!=-1].sum()
        final_score = draw*remaining_board_sum
        print(f'Winning board: {i} \nBoard State: \n{board} \nFinal Score: {final_score}')
        done=True

Winning board: 41 
Board State: 
[[17  6 -1 27 64]
 [14 34 -1 -1 40]
 [-1 97 -1 57 88]
 [-1 79 -1 31  2]
 [15 99 -1 62 50]] 
Final Score: 46920


## Part 2

In [293]:
dones=np.zeros(boards_array.shape[0], dtype=int)
boards_array = np.copy(initial_boards_array)

for draw in draws:
  boards_array[boards_array==draw]=-1
  for i, done in enumerate(dones):
    if done==0:
      board = boards_array[i,:,:]
      if np.any(board.sum(0)==boards_shape[0]*-1) or np.any(board.sum(1)==boards_shape[1]*-1):
        dones[i]=1
      if dones.sum()==boards_array.shape[0]:
        losing_board_index = i
        losing_board = boards_array[losing_board_index,:,:]
        losing_board_sum = losing_board[board[:,:]!=-1].sum()
        losing_board_final_score = draw*losing_board_sum
        print(f'Losing board: {losing_board_index} \nLosing Board State: \n{losing_board} \nLosing Final Score: {losing_board_final_score}')

Losing board: 29 
Losing Board State: 
[[-1 -1 -1 -1 18]
 [-1 97 -1 73 64]
 [-1 99 -1 -1 -1]
 [-1 -1 10 -1 -1]
 [-1 -1 -1 -1 -1]] 
Losing Final Score: 12635
